# ==============================================================================
# General

# Optional session examples. XWayland support is enabled by default.
# https://docs.noctalia.dev/umbriel/configuration/#general

[general]
autostart = ["noctalia"]
mod_key = "Super"
xwayland = true
xwayland_native_resolution = true
show_cheatsheet = true
focus_on_activate = true
honor_restored_maximize = true
